export const Locators = {
    inputLogin: '#user-name',
    inputPassword: '#password',
    buttonLogin: '#login-button',
    inventoryContainer: '#inventory_container .inventory_item',
    badgeIconPrincipalPage: ".shopping_cart_container",
    itemName: " .inventory_item_name",
    itemDescription: " .inventory_item_desc",
    itemPrice: " .inventory_item_price",
    badgeIcon: "//span[@data-test='shopping-cart-badge']",
    buttonCheckout: '#checkout',
    buttonContinueShopping: "#continue-shopping",
    buttonCancelPurchase: "#cancel",
    buttonContinuePurchase: "#continue",
    inputFirstName: "#first-name",
    inputLastName: "#last-name",
    inputZipCode: "#postal-code",
    buttonCancel: "#cancel",
    buttonFinish: "#finish",
    headerComplete: ".complete-header",
    imagePony: "//img[@class='pony_express']",
    buttonBackHome: "#back-to-products",
}